# Site Settings
lang: en
title: graft
tagline: cultivate new knowledge
email: keith@graftapp.co
description: >
  Graft is a personal knowledge graph that acts like an extension of your working memory. Explore the meaningful connections between your knowledge and unlock new insights.
url: "https://www.graftapp.co"

timezone: Etc/UTC

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json

livereload: true

sass:
  style: compressed
  source_dir: _sass
