name: Website Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - uses: actions/setup-ruby@v1
              with:
                ruby-version: '2.6'
            - uses: actions/setup-node@v2
              with:
                  node-version: '12'
            - name: NPM Install
              run: |
                  npm ci
            - name: Build dev app
              uses: helaili/jekyll-action@v2
              with:
                build_only: true
            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_DEV_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
                  SOURCE_DIR: '_site'
